# Generated by Django 2.1.15 on 2019-12-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181008_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='pub_date',
        ),
    ]
